// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://icemgkxzmpttrnjbdvaq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImljZW1na3h6bXB0dHJuamJkdmFxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMzNzY2MDcsImV4cCI6MjA2ODk1MjYwN30._3hEnk6sK6dV90GrH75C2TZboLO5TCPmPm7ubFV6H5w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});